In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [36]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [37]:
dataset

,age,sex,bmi,children,smoker,charges
0,19,female,27.900,0,yes,16884.92400
1,18,male,33.770,1,no,1725.55230
2,28,male,33.000,3,no,4449.46200
3,33,male,22.705,0,no,21984.47061
4,32,male,28.880,0,no,3866.85520
...,...,...,...,...,...,...
1333,50,male,30.970,3,no,10600.54830
1334,18,female,31.920,0,no,2205.98080
1335,18,female,36.850,0,no,1629.83350
1336,21,female,25.800,0,no,2007.94500
1337,...,female,29.070,0,yes,29141.36030

In [38]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='str')

In [39]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [40]:
dataset

,bmi,children,charges,age_18,age_19,age_20,age_21,age_22,age_23,age_24,...,age_57,age_58,age_59,age_60,age_61,age_62,age_63,age_64,sex_male,smoker_yes
0,27.900,0,16884.92400,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,33.770,1,1725.55230,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,33.000,3,4449.46200,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,22.705,0,21984.47061,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,28.880,0,3866.85520,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,30.970,3,10600.54830,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1334,31.920,0,2205.98080,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1335,36.850,0,1629.83350,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1336,25.800,0,2007.94500,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1337,29.070,0,29141.36030,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [41]:
indep=dataset[['bmi', 'children','age_18', 'age_19', 'age_20', 'age_21',
       'age_22', 'age_23', 'age_24', 'age_25', 'age_26', 'age_27', 'age_28',
       'age_29', 'age_30', 'age_31', 'age_32', 'age_33', 'age_34', 'age_35',
       'age_36', 'age_37', 'age_38', 'age_39', 'age_40', 'age_41', 'age_42',
       'age_43', 'age_44', 'age_45', 'age_46', 'age_47', 'age_48', 'age_49',
       'age_50', 'age_51', 'age_52', 'age_53', 'age_54', 'age_55', 'age_56',
       'age_57', 'age_58', 'age_59', 'age_60', 'age_61', 'age_62', 'age_63',
       'age_64', 'sex_male', 'smoker_yes']]
dep=dataset[["charges"]]

In [42]:
indep

,bmi,children,age_18,age_19,age_20,age_21,age_22,age_23,age_24,age_25,...,age_57,age_58,age_59,age_60,age_61,age_62,age_63,age_64,sex_male,smoker_yes
0,27.900,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,33.770,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,33.000,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,22.705,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,28.880,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,30.970,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1334,31.920,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1335,36.850,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1336,25.800,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1337,29.070,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [43]:
dep

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [44]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [45]:
X_train

,bmi,children,age_18,age_19,age_20,age_21,age_22,age_23,age_24,age_25,...,age_57,age_58,age_59,age_60,age_61,age_62,age_63,age_64,sex_male,smoker_yes
482,31.35,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
338,32.30,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
356,43.89,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
869,24.30,3,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
182,19.95,3,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,26.03,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
835,35.97,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1216,25.08,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
559,35.53,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
684,18.50,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
X_train.shape

(892, 51)

In [47]:
y_train

         charges
482    1622.1885
338   41919.0970
356    8944.1151
869    4391.6520
182    4005.4225
...          ...
763    3070.8087
835    7160.3303
1216   5415.6612
559    1646.4297
684    4766.0220

[892 rows x 1 columns]

In [48]:
y_train.shape

(892, 1)

In [49]:
X_test

,bmi,children,age_18,age_19,age_20,age_21,age_22,age_23,age_24,age_25,...,age_57,age_58,age_59,age_60,age_61,age_62,age_63,age_64,sex_male,smoker_yes
578,30.200,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
610,29.370,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
569,40.565,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
1034,38.380,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
198,18.050,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,26.840,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1271,34.485,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1313,34.700,2,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,33.000,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
405,38.380,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
X_test.shape

(446, 51)

In [51]:
y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
261   17085.26760
1271   3021.80915
1313  36397.57600
2      4449.46200
405   11396.90020

[446 rows x 1 columns]

In [52]:
y_test.shape

(446, 1)

In [53]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)#y=W*x1+b0 for this equation we got value for b1 and bo

LinearRegression()

In [54]:
# Viewing the b1 and bo value
weight=regressor.coef_
print("Weight of the model={}".format(weight))
bais=regressor.intercept_
print("Intercept of the model={}".format(bais))

Weight of the model=[[  312.08349619   680.75767945 -5626.28767987 -5272.67530262
  -5266.4783315  -5634.17539218 -3935.89969431 -3852.11082234
  -1867.07527433 -4033.01333814 -3515.26430383 -3474.47006514
  -1817.58482288 -2573.34097148 -4381.60649154 -2393.75369835
  -5013.11453491 -1527.38330021 -2376.34154672 -2678.74858249
  -2720.57674675   129.68886537 -2991.62547255 -3001.62130627
  -2039.75387016 -1104.81429733 -2165.23621642 -1226.04252598
   1530.84426981  3862.45464663  1223.02745121  1021.89359946
    716.26283008   422.31812072  3540.11110278  1897.34781276
   4151.80951745  2359.02309845  5405.52124381  5900.94970284
   2692.89320729  3075.4241898   2843.96542049  6547.6841133
   7985.88868338  7366.12358732  6460.53277721  5156.39949691
   6198.83085126   -30.50299297 23304.28350169]]
Intercept of the model=[-1434.28369578]

In [55]:
y_pred=regressor.predict(X_test)

In [56]:
#https://scikit-learn.org/stable/modules/model_evaluation.html

In [57]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [58]:
r_score

0.7862161705648972

In [65]:
import pickle

In [27]:
filename="mulline_final.sav"
pickle.dump(regressor,open(filename,"wb"))

In [66]:
model=pickle.load(open(filename,"rb"))

In [67]:
rd_input=float(input("R&D:"))
admin_input=float(input("Admin"))
mark_input=float(input("Marketing "))
fol_input=int(input("State_flo 0 or 1:"))
new_input=int(input("State_new 0 or 1:"))

R&D: 44500
Admin 50800
Marketing  56405
State_flo 0 or 1: 1
State_new 0 or 1: 0

In [68]:
result=model.predict([[rd_input,admin_input,mark_input,fol_input,new_input]])

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [69]:
result

array([[85749.46797074]])